// <auto-generated />
using System;
using BoxApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoxApplication.Migrations
{
    [DbContext(typeof(BoxApplicationContext))]
    [Migration("20190215024831_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoxApplication.Models.ActiveDirectoryUser", b =>
                {
                    b.Property<string>("ADEmail")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ADDateInactive");

                    b.Property<string>("ADFirstName");

                    b.Property<string>("ADStatus");

                    b.Property<string>("ADUsername");

                    b.HasKey("ADEmail");

                    b.ToTable("ActiveDirectoryUser");
                });
#pragma warning restore 612, 618
        }
    }
}
