// <auto-generated />
using System;
using BoxApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoxApplication.Migrations
{
    [DbContext(typeof(BoxApplicationContext))]
    [Migration("20190401003456_UpdatedActiveDirectory")]
    partial class UpdatedActiveDirectory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoxApplication.Models.ActiveDirectoryUser", b =>
                {
                    b.Property<byte[]>("ADGUID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ADDateModified");

                    b.Property<string>("ADEmail");

                    b.Property<string>("ADFullName");

                    b.Property<string>("ADStatus");

                    b.HasKey("ADGUID");

                    b.ToTable("ActiveDirectoryUsers");
                });

            modelBuilder.Entity("BoxApplication.Models.ApplicationAction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Type");

                    b.Property<string>("User");

                    b.HasKey("ID");

                    b.ToTable("ApplicationActions");
                });

            modelBuilder.Entity("BoxApplication.Models.BoxADUpdate", b =>
                {
                    b.Property<Guid>("BoxADUpdateID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ADFieldChanged");

                    b.Property<string>("ADNewData");

                    b.Property<string>("BoxID");

                    b.Property<string>("BoxPreviousData");

                    b.Property<string>("BoxUserID");

                    b.HasKey("BoxADUpdateID");

                    b.HasIndex("BoxUserID");

                    b.ToTable("BoxADUpdates");
                });

            modelBuilder.Entity("BoxApplication.Models.BoxUsers", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("ADGUID");

                    b.Property<bool>("Active");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<long>("SpaceUsed");

                    b.HasKey("ID");

                    b.HasIndex("ADGUID");

                    b.ToTable("BoxUsers");
                });

            modelBuilder.Entity("BoxApplication.Models.BoxADUpdate", b =>
                {
                    b.HasOne("BoxApplication.Models.BoxUsers", "BoxUser")
                        .WithMany()
                        .HasForeignKey("BoxUserID");
                });

            modelBuilder.Entity("BoxApplication.Models.BoxUsers", b =>
                {
                    b.HasOne("BoxApplication.Models.ActiveDirectoryUser", "aduser")
                        .WithMany()
                        .HasForeignKey("ADGUID");
                });
#pragma warning restore 612, 618
        }
    }
}
