// <auto-generated />
using System;
using BoxApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoxApplication.Migrations
{
    [DbContext(typeof(BoxApplicationContext))]
    partial class BoxApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoxApplication.Models.ActiveDirectoryUser", b =>
                {
                    b.Property<string>("ADEmail")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ADDateInactive");

                    b.Property<string>("ADFirstName");

                    b.Property<string>("ADStatus");

                    b.Property<string>("ADUsername");

                    b.HasKey("ADEmail");

                    b.ToTable("ActiveDirectoryUser");
                });

            modelBuilder.Entity("BoxApplication.Models.ApplicationAction", b =>
                {
                    b.Property<Guid>("ApplicationActionID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationActionADForeignKey");

                    b.Property<DateTime>("ApplicationActionDate");

                    b.Property<string>("ApplicationActionDescription");

                    b.Property<string>("ApplicationActionObjectModified");

                    b.Property<string>("ApplicationActionType");

                    b.HasKey("ApplicationActionID");

                    b.HasIndex("ApplicationActionADForeignKey");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("BoxApplication.Models.BoxUser", b =>
                {
                    b.Property<string>("BoxID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BoxADForeignKey");

                    b.Property<DateTime>("BoxDateCreated");

                    b.Property<DateTime>("BoxDateModified");

                    b.Property<string>("BoxLogin");

                    b.Property<string>("BoxName");

                    b.Property<int>("BoxSpaceUsed");

                    b.Property<string>("BoxStatus");

                    b.HasKey("BoxID");

                    b.HasIndex("BoxADForeignKey");

                    b.ToTable("BoxUser");
                });

            modelBuilder.Entity("BoxApplication.Models.ApplicationAction", b =>
                {
                    b.HasOne("BoxApplication.Models.ActiveDirectoryUser", "ApplicationActionADUser")
                        .WithMany()
                        .HasForeignKey("ApplicationActionADForeignKey");
                });

            modelBuilder.Entity("BoxApplication.Models.BoxUser", b =>
                {
                    b.HasOne("BoxApplication.Models.ActiveDirectoryUser", "BoxEmail")
                        .WithMany()
                        .HasForeignKey("BoxADForeignKey");
                });
#pragma warning restore 612, 618
        }
    }
}
